package wrm.libsass.api;
import com.sun.jna.Library;
/**
 * JNA Wrapper for library <b>sass_interface</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface LibSassDll extends Library {
  /**
   * Original signature : <code>sass_context* sass_new_context()</code><br>
   * <i>native declaration : sass_interface.h:83</i>
   */
  sass_context sass_new_context();
  /**
   * Original signature : <code>sass_file_context* sass_new_file_context()</code><br>
   * <i>native declaration : sass_interface.h:84</i>
   */
  sass_file_context sass_new_file_context();
  /**
   * Original signature : <code>sass_folder_context* sass_new_folder_context()</code><br>
   * <i>native declaration : sass_interface.h:85</i>
   */
  sass_folder_context sass_new_folder_context();
  /**
   * Original signature : <code>void sass_free_context(sass_context*)</code><br>
   * <i>native declaration : sass_interface.h:87</i>
   */
  void sass_free_context(sass_context ctx);
  /**
   * Original signature : <code>void sass_free_file_context(sass_file_context*)</code><br>
   * <i>native declaration : sass_interface.h:88</i>
   */
  void sass_free_file_context(sass_file_context ctx);
  /**
   * Original signature : <code>void sass_free_folder_context(sass_folder_context*)</code><br>
   * <i>native declaration : sass_interface.h:89</i>
   */
  void sass_free_folder_context(sass_folder_context ctx);
  /**
   * Original signature : <code>int sass_compile(sass_context*)</code><br>
   * <i>native declaration : sass_interface.h:91</i>
   */
  int sass_compile(sass_context ctx);
  /**
   * Original signature : <code>int sass_compile_file(sass_file_context*)</code><br>
   * <i>native declaration : sass_interface.h:92</i>
   */
  int sass_compile_file(sass_file_context ctx);
  /**
   * Original signature : <code>int sass_compile_folder(sass_folder_context*)</code><br>
   * <i>native declaration : sass_interface.h:93</i>
   */
  int sass_compile_folder(sass_folder_context ctx);
}
