package wrm.libsass.api;
import java.util.Arrays;
import java.util.List;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : line 32</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sass_folder_context extends Structure {
	/// C type : char*
	public Pointer search_path;
	/// C type : char*
	public Pointer output_path;
	/// C type : sass_options
	public sass_options options;
	public int error_status;
	/// C type : char*
	public Pointer error_message;
	public sass_folder_context() {
	}
	/**
	 * @param search_path C type : char*<br>
	 * @param output_path C type : char*<br>
	 * @param options C type : sass_options<br>
	 * @param error_message C type : char*
	 */
	public sass_folder_context(Pointer search_path, Pointer output_path, sass_options options, int error_status, Pointer error_message) {
		super();
		this.search_path = search_path;
		this.output_path = output_path;
		this.options = options;
		this.error_status = error_status;
		this.error_message = error_message;
	}
	@Override
	protected List getFieldOrder() {
		return Arrays.asList("search_path", "output_path", "options", "error_status", "error_message");
	};
}